{% set name = "arrow_odbc" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a69f2199f0acaf16b6efcbc5683602940ae7d0bbf1e8283ff62dc285f17b9e8b

build:
  number: 0
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m build --no-isolation
    - {{ PYTHON }} -m pip install dist/*.whl --no-deps
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - unixodbc
  host:
    - python
    - python-build
    - cffi
    - maturin >=0.13,<0.14
    - milksnake
    - pip
    - pyarrow
    - unixodbc
  run:
    - python
    - cffi
    - pyarrow

test:
  imports:
    - arrow_odbc


outputs:
  - name: arrow_odbc
  - name: arrow-odbc
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("arrow_odbc", exact=True) }}

    test:
      imports:
        - arrow_odbc


about:
  home: https://github.com/pacman82/arrow-odbc-py
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Read Apache Arrow batches from ODBC data sources in Python
  dev_url: https://github.com/pacman82/arrow-odbc-py

extra:
  recipe-maintainers:
    - timkpaine
    - pacman82
