{% set name = "arrow_odbc" %}
{% set version = "5.1.0" %}
{% set build_num = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b53f6fda3f6d3e2b653c1517d29fc7dce15c20c290ea8f4c94a0fdfa7218f414

build:
  number: {{ build_num }}
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" {{ PYTHON }} -m build --no-isolation  # [unix]
    - {{ PYTHON }} -m build --no-isolation                                            # [win]
    - {{ PYTHON }} -m pip install --no-deps --find-links dist arrow_odbc
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - maturin >=1,<2                      # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-build
    - cffi
    - maturin >=1,<2
    - milksnake
    - pip
    - pyarrow >=8
    - unixodbc  # [not win]
    - libiconv  # [osx]
  run:
    - python
    - cffi
    - pyarrow >=8

test:
  imports:
    - arrow_odbc


outputs:
  - name: arrow_odbc
  - name: arrow-odbc
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - arrow_odbc ={{ version }}=*_{{ build_num }}

    test:
      imports:
        - arrow_odbc


about:
  home: https://github.com/pacman82/arrow-odbc-py
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Read Apache Arrow batches from ODBC data sources in Python
  dev_url: https://github.com/pacman82/arrow-odbc-py

extra:
  recipe-maintainers:
    - jonashaag
    - timkpaine
    - pacman82
