{% set name = "arrow_odbc" %}
{% set version = "9.2.0" %}
{% set build_num = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2eeb8f5ddc2bcf3d8a30fe7a1a677358ac1bc973c813c6c44e43839655cf895

build:
  number: {{ build_num }}
  script:
    - export RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib"  # [unix]
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation .
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - maturin >=1,<2                      # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-build
    - cffi
    - maturin >=1,<2
    - pip
    - pyarrow >=8
    - unixodbc  # [not win]
    - libiconv  # [osx]
  run:
    - python
    - cffi
    - pyarrow >=8

test:
  imports:
    - arrow_odbc

about:
  home: https://github.com/pacman82/arrow-odbc-py
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Read Apache Arrow batches from ODBC data sources in Python
  dev_url: https://github.com/pacman82/arrow-odbc-py

extra:
  recipe-maintainers:
    - jonashaag
    - timkpaine
    - pacman82
